"""rename address

Revision ID: f31e6fd9ea69
Revises: e0348a83ff7e
Create Date: 2024-06-13 17:56:18.020377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f31e6fd9ea69'
down_revision = 'e0348a83ff7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
        op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
